services:
  api:
    restart: always
    build:
      context: api
      dockerfile: docker/dev/Dockerfile
    env_file:
      - api/docker/dev/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=timeline
    ports:
      - "5432:5432"
