[package]
name = "timeline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
jsonwebtoken = "7.2.0"
serde = { version = "1.0.130", features = ["derive"] }
