name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: timeline
        options: >-
          --health-interval 10s
          --health-cmd pg_isready
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: api

      - run: |
          cd api
          cargo check
          cargo test
        name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/timeline

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: api

      - run: |
          cd api
          cargo fmt -- --check
        name: Check formatting

      - run: |
          cd api
          cargo clippy --all-targets --all-features
        name: Check linting
